version: "3.9"
services:

  app:
    image: security-policy
    build: .
    ports:
      - "8000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

